name: prosmith
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  - tqdm
  - rdkit
  - astartes
  - configargparse
  - scikit-learn
  - pip
  - pip:
    - pandas
    - numpy
    - biopython
    - transformers
    - lifelines
    - xgboost
    - hyperopt
    - fair-esm
    - wandb
